changelog:
  categories:
    - title: "Minecraft Update"
      labels:
        - "minecraft update"

    - title: "New Features"
      labels:
        - "feature"

    - title: "Bug Fixes"
      labels:
        - "bug"

    - title: "Optimizations"
      labels:
        - "optimization"

    - title: "Changes & Enhancements"
      labels:
        - "refactor"
        - "enhancement"

    - title: "Dependencies"
      labels:
        - "renovate"

    - title: "Other"
      labels:
        - "*"