# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  profile: assertive
  high_level_summary: false
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  in_progress_fortune: false
  poem: false
  enable_prompt_for_ai_agents: false
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  review_status: false
chat:
  art: false
  auto_reply: false
  integrations:
    jira:
      usage: disabled
    linear:
      usage: disabled
knowledge_base:
  web_search:
    enabled: false
issue_enrichment:
  auto_enrich:
    enabled: false
  planning:
    enabled: false
    auto_planning:
      enabled: false
