name: NiveriaHolograms
version: '${version}'
main: toutouchien.niveriaholograms.NiveriaHolograms
api-version: '${minecraftVersion}'
load: STARTUP
authors: [ Toutouchien ]
website: niveria.fr

dependencies:
  server:
    NiveriaAPI:
      load: BEFORE
      required: true