name: NiveriaHolograms
version: '${version}'
main: toutouchien.niveriaholograms.NiveriaHolograms
api-version: '${minMinecraftVersion}'
load: STARTUP
authors: [ PuppyTransGirl ]

dependencies:
  server:
    NiveriaAPI:
      load: BEFORE
      required: true